// TODO 서버에서 데이터 가져오기
export const fetchData = () => {
  const data = {
    studyInfoList: [
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
      {
        patientId: "120",
        studyDate: "2022-02-21 13:00:00",
        accesionNo: "2171410",
        studyDescription: "Study Description",
        modality: "CT",
        ser: "4",
        ins: "4",
        name: "Patient Name 1",
        gender: "M",
      },
    ],
  };

  return { data };
};
